### PR TITLE
Feature/add service content type

### PR DESCRIPTION
**Pull request by eric-gu**
Add "Service" content type and page
https://app.asana.com/0/1132578874282309/1144271015845475

### CODE REVIEW

**Comment by abeal-hottomali** [comment]
This PR broke on me during local installation:

```
 [notice] Starting Drupal installation. This takes a while.

In install.core.inc line 974:

  The configuration cannot be imported because it failed validation for the followin
  g reasons:<div class="item-list"><ul><li>Unable to install the <em class="placehol
  der">Icon Select</em> module since it requires the <em class="placeholder">Hook Po
  st Action</em> module.</li></ul></div>


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...

task failed: Exec command 'drush si config_installer --account-name=admin --account-pass=123456 -y' in container/service 'web': Failed to run docker-compose [-f /Users/aronbeal/Sites/hottomali/bwinsurance/2.0/.ddev/docker-compose.yaml -f /Users/aronbeal/Sites/hottomali/bwinsurance/2.0/.ddev/docker-compose.override.yaml exec -w /var/www/html/web -T web bash -c drush si config_installer --account-name=admin --account-pass=123456 -y], err='exit status 1', stdout='
 // You are about to DROP all tables in your 'db' database. Do you want to continue?:
 // yes.
```

**Comment by abeal-hottomali** [comment]
Note: develop, with 8.7.11 update has been merged into this branch. Problem with site-rebuild is still unresolved.

**Comment by eric-gu** [comment]
Fixed

**Comment by abeal-hottomali** [comment]
image

Eric, I'm going to merge this in so folks can get started, although I'd like to talk with you soon about how the content folks should be mocking things up.  If you can, port an example online that they can draw from once this goes live?

**Pull request merged**
