### PR TITLE
[WIP] (add-insurance-content-types) Add basic content types

### PR DESCRIPTION
**Pull request by JujharH**
Add basic content types with one example of each.

https://app.asana.com/0/1132578874282309/1144254098499955/f

### CODE REVIEW

**Comment by abeal-hottomali** [comment]
Eric, would you mind reviewing this work as part of the associated Asana task (linked above), and bounce it back to me if you think it's completed?  No urgency, complete whenever you are between tasks.

**Comment by eric-gu** [comment]
The code works. However, I am a little bit confused, why 3 new content types?
Highlighted features (I've created a new custom block type for same purpose)
Insurance types
Insurance types personal (should this be a page of Insurance type?)

**Comment by eric-gu** [comment]
Use Paragraph for the highlighted features could be also a good idea, as those content are not likely to be re-used.

**Comment by abeal-hottomali** [comment]
> The code works. However, I am a little bit confused, why 3 new content types?
> Highlighted features (I've created a new custom block type for same purpose)
> Insurance types
> Insurance types personal (should this be a page of Insurance type?)

I'm not sure about "Insurance Types Personal" - I don't think that was part of the original spec.  I had ["Insurance Type"](https://app.asana.com/0/1132578874282309/1144254098499955), ["Service"](https://app.asana.com/0/1132578874282309/1144271015845475), and ["Location"](https://app.asana.com/0/1132578874282309/1132770960999618) as expected types, I believe.  Does that match with your expectation?

**Comment by abeal-hottomali** [comment]
> Use Paragraph for the highlighted features could be also a good idea, as those content are not likely to be re-used.

I'm good with that.

**Comment by abeal-hottomali** [comment]
Awaiting response to question in slack: https://hottomali.slack.com/archives/DR4N9QJLT/p1580236551003200

**Comment by abeal-hottomali** [comment]
Eric, can you please resolve the conflicts that have arisen between this branch and `develop` after the merge of [content-migration](https://github.com/Hot-Tomali/bwinsurance2/pull/20).

**Comment by abeal-hottomali** [comment]
Scheduled for release in https://app.asana.com/0/1140921080025377/1159680946639633 once merge conflicts are addressed.

**Comment by abeal-hottomali** [comment]
Released in https://app.asana.com/0/1140921080025377/1159680946639633

**Pull request merged**
