### PR TITLE
Feature/add remote media support

### PR DESCRIPTION
**Pull request by eric-gu**
https://app.asana.com/0/1132578874282309/1132770960999662

### CODE REVIEW

**Comment by eric-gu** [comment]
For Prod, before importing config, add following to settings.local.php:
(Replace values in first 4 lines)

$settings['s3fs.access_key'] = 'your access key';
$settings['s3fs.secret_key'] = 'your secret key';
$config['s3fs.settings']['bucket'] = 's3-bucket-name';
$config['s3fs.settings']['region'] = 's3-bucket-region';
$settings['s3fs.use_s3_for_public'] = TRUE;
# if you want to use S3 for private files, uncomment the line below:
#$settings['s3fs.use_s3_for_private'] = TRUE;
$settings['php_storage']['twig']['directory'] = '../storage/php';

**Comment by abeal-hottomali** [comment]
Note: when I rebuild this branch, the s3fs module is not enabled.  When I enable it, the CSS and JS break:

image

**Comment by abeal-hottomali** [comment]
Eric, this is back to you for review.  Please note the slack message I've added for the required credentials to access the associated S3 bucket.

Note: I've already merged the 8.7.11 update from develop into this one.

**Comment by abeal-hottomali** [comment]
I need to get this out to production, so I'm merging it.

**Pull request merged**
